### ISSUE TITLE
RNAndrow was not found

### ISSUE THREAD

**Issue by partitect** [WrathChaos/react-native-beautiful-timeline#2]
Timeline work on ios but dosn't work andorid 

requireNativeComponent: "RNAndrow" was not found in the UIManager

i installed yarn add react-native-androw

`import React from "react";
import { ScrollView } from "react-native";

import Timeline from "react-native-beautiful-timeline";

const datass = [
  {
    date: 1574342522000,
    data: [
      {
        title: "React Native Beautiful Timeline",
        subtitle: "Sed at justo eros. Phasellus.",
        date: 1574342522000
      },
      {
        title: "React Native",
        subtitle: "Sed viverra. Nam sagittis.",
        date: 1574342501000
      }
    ]
  },
  {
    date: 1574248261000,
    data: [
      {
        title: "Timeline",
        subtitle: "Morbi magna orci, consequat in.",
        date: 1574248261000
      }
    ]
  },
  {
    date: 1574125621000,
    data: [
      {
        title: "Beauty Timeline",
        subtitle: "Nulla a eleifend urna. Morbi. Praesent.",
        date: 1574125621000
      }
    ]
  }
];

export const Message = () => {
  return (
    
      <Timeline data={datass} />
   
  );
};
`

**Comment by partitect** [comment]
when download code and manual import from local path and delete Androw View its work

**Comment by kuraydev** [comment]
Can you share with me a minimal reproducible example? Because I cannot reproduce it on Android as well. Are you sure that you installed the androw correctly?

**Comment by opmat** [comment]
I also have this issue using React Native (Expo managed). How can we solve it?
