### ISSUE TITLE
Underlying flatlist?

### ISSUE THREAD

**Issue by kinkin626** [WrathChaos/react-native-beautiful-timeline#28]
I haven't checked the code beneath yet, but does this library use flatlist, if yes onendreached and other params can be passed?

Edit: the library uses flatlist, but there is no way to pass other props as required

**Comment by kuraydev** [comment]
Hello @kinkin626 
The new version is in development, I will make it possible to use all other props for flatlist :)

**Comment by kinkin626** [comment]
Thanks @WrathChaos any ETA for the same?

**Comment by kuraydev** [comment]
@kinkin626 Probably I will publish it today :) 

Edit:

Unfortunately I could not have a chance to finish it today, tomorrow I will finish the work and publish it

**Comment by kuraydev** [comment]
Hello again @kinkin626 
Version 1.0.1 is here :) 

There is new dependency so please take a look at the documentation first.
Also, flatlist takes the all props now :)

**Comment by kinkin626** [comment]
Hey, thank you, really appreciate the support. Will check and let you know.
