### ISSUE TITLE
Can't find variable: renderItem

### ISSUE THREAD

**Issue by dlogvin** [WrathChaos/react-native-beautiful-timeline#4]
Hello! 

I'll just go straight to the point:

```
{
    this.state.progresses.map(progress => {
        const data = {
            date: progress.created_at,
            title: progress.title,
            subtitle: progress.description
        }
        return(
            <View>
                <Timeline data={data} />
            </View>
        )
    })
}
```
That's my code... I'm indeed sure this thing is wrong (my code). But at the same time, I cannot understand what's wrong with `renderItem`

**Comment by kuraydev** [comment]
Hello @danslabs,
As I understand, your data is wrong. It should be an array. Also, why do you create more than one Timeline within the .map ? Timeline itself handle the more than one data. Have you checked the example? 
## [Example](https://github.com/WrathChaos/react-native-beautiful-timeline/tree/master/example )
